'use client'

import { useState } from 'react'
import { FileText, Download, Eye, Share2, Calendar } from 'lucide-react'

interface ConsultationReport {
  id: string
  patientName: string
  doctorName: string
  date: string
  duration: number
  chiefComplaint: string
  history: string
  assessment: string
  plan: string
  medications: string[]
  followUp: string
  recommendations: string[]
}

export default function ReportGenerator() {
  const [reports, setReports] = useState<ConsultationReport[]>([
    {
      id: 'rep_1',
      patientName: 'John Smith',
      doctorName: 'Dr. Sarah Johnson',
      date: new Date().toISOString(),
      duration: 30,
      chiefComplaint: 'Persistent headache and dizziness',
      history: 'Patient reports 2-week history of intermittent headaches with associated dizziness. No fever, nausea, or visual changes.',
      assessment: 'Tension-type headache likely. Blood pressure within normal limits. Neurological exam unremarkable.',
      plan: '1. Monitor headache frequency and triggers\n2. Consider OTC analgesics as needed\n3. Follow up in 2 weeks',
      medications: ['Ibuprofen 400mg PRN', 'Hydration advice'],
      followUp: '2 weeks',
      recommendations: ['Maintain headache diary', 'Practice stress management', 'Ensure adequate hydration']
    }
  ])

  const generateNewReport = () => {
    const newReport: ConsultationReport = {
      id: `rep_${Date.now()}`,
      patientName: 'New Patient',
      doctorName: 'Dr. MediAI Assistant',
      date: new Date().toISOString(),
      duration: 25,
      chiefComplaint: 'Automated consultation summary',
      history: 'AI-assisted consultation with comprehensive symptom analysis and medical history review.',
      assessment: 'AI-generated assessment based on consultation dialogue and medical knowledge base.',
      plan: '1. Review AI recommendations\n2. Consider suggested diagnostics\n3. Implement treatment plan',
      medications: ['As per physician discretion'],
      followUp: 'As needed',
      recommendations: ['Follow AI-generated care plan', 'Monitor symptoms', 'Schedule follow-up']
    }
    
    setReports(prev => [newReport, ...prev])
  }

  const downloadReport = (report: ConsultationReport) => {
    const reportContent = generateReportContent(report)
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `consultation-report-${report.id}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const generateReportContent = (report: ConsultationReport): string => {
    return `
MEDICAL CONSULTATION REPORT
Generated by MediAI Pro Assistant

PATIENT INFORMATION:
-------------------
Name: ${report.patientName}
Date: ${new Date(report.date).toLocaleDateString()}
Duration: ${report.duration} minutes
Physician: ${report.doctorName}

CHIEF COMPLAINT:
---------------
${report.chiefComplaint}

HISTORY OF PRESENT ILLNESS:
--------------------------
${report.history}

ASSESSMENT:
----------
${report.assessment}

TREATMENT PLAN:
--------------
${report.plan}

MEDICATIONS:
-----------
${report.medications.map(med => `• ${med}`).join('\n')}

FOLLOW-UP:
---------
${report.followUp}

RECOMMENDATIONS:
---------------
${report.recommendations.map(rec => `• ${rec}`).join('\n')}

AI INSIGHTS:
-----------
• Consultation analyzed using advanced medical AI
• Drug interaction checks performed
• Evidence-based treatment recommendations
• Risk assessment completed

CONFIDENTIALITY NOTICE:
----------------------
This document contains protected health information (PHI).
Unauthorized access or disclosure prohibited.

Generated: ${new Date().toISOString()}
MediAI Pro - Advanced Medical AI Assistant
    `.trim()
  }

  const shareReport = (report: ConsultationReport) => {
    // In production, integrate with email or messaging systems
    const reportContent = generateReportContent(report)
    console.log('Sharing report:', reportContent)
    alert('Report ready for sharing. In production, this would integrate with your communication systems.')
  }

  return (
    <div className="p-4 space-y-4">
      {/* Generate New Report Button */}
      <button
        onClick={generateNewReport}
        className="w-full py-3 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-lg font-medium hover:from-blue-600 hover:to-purple-600 transition-all transform hover:scale-[1.02]"
      >
        <FileText className="w-5 h-5 inline mr-2" />
        Generate AI Consultation Report
      </button>

      {/* Reports List */}
      <div className="space-y-4 max-h-96 overflow-y-auto">
        {reports.map((report) => (
          <div key={report.id} className="bg-muted/50 rounded-lg border border-border p-4">
            {/* Report Header */}
            <div className="flex items-center justify-between mb-3">
              <div>
                <h3 className="font-semibold text-foreground">{report.patientName}</h3>
                <p className="text-sm text-muted-foreground flex items-center gap-1">
                  <Calendar className="w-3 h-3" />
                  {new Date(report.date).toLocaleDateString()} • {report.duration}min
                </p>
              </div>
              <div className="flex gap-1">
                <button
                  onClick={() => downloadReport(report)}
                  className="p-2 text-primary hover:bg-primary/10 rounded transition-colors"
                  title="Download report"
                >
                  <Download className="w-4 h-4" />
                </button>
                <button
                  onClick={() => shareReport(report)}
                  className="p-2 text-green-600 hover:bg-green-500/10 rounded transition-colors"
                  title="Share report"
                >
                  <Share2 className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Report Preview */}
            <div className="space-y-2 text-sm">
              <div>
                <strong>Chief Complaint:</strong> {report.chiefComplaint}
              </div>
              <div>
                <strong>Assessment:</strong> {report.assessment.substring(0, 100)}...
              </div>
              <div className="flex flex-wrap gap-1">
                {report.medications.slice(0, 2).map((med, index) => (
                  <span key={index} className="px-2 py-1 bg-blue-500/10 text-blue-700 dark:text-blue-300 rounded text-xs">
                    {med}
                  </span>
                ))}
                {report.medications.length > 2 && (
                  <span className="px-2 py-1 bg-gray-500/10 text-gray-600 rounded text-xs">
                    +{report.medications.length - 2} more
                  </span>
                )}
              </div>
            </div>

            {/* AI Badge */}
            <div className="mt-3 pt-3 border-t border-border">
              <span className="inline-flex items-center gap-1 px-2 py-1 bg-gradient-to-r from-purple-500 to-blue-500 text-white text-xs rounded-full">
                <FileText className="w-3 h-3" />
                AI-Generated Report
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Report Statistics */}
      <div className="grid grid-cols-3 gap-2 text-center">
        <div className="p-2 bg-blue-500/10 rounded">
          <div className="text-lg font-bold text-blue-600">{reports.length}</div>
          <div className="text-xs text-muted-foreground">Reports</div>
        </div>
        <div className="p-2 bg-green-500/10 rounded">
          <div className="text-lg font-bold text-green-600">
            {reports.reduce((acc, report) => acc + report.duration, 0)}
          </div>
          <div className="text-xs text-muted-foreground">Total Minutes</div>
        </div>
        <div className="p-2 bg-purple-500/10 rounded">
          <div className="text-lg font-bold text-purple-600">
            {new Set(reports.map(r => r.patientName)).size}
          </div>
          <div className="text-xs text-muted-foreground">Patients</div>
        </div>
      </div>
    </div>
  )
}
